//each room has a name "A" for instance. World Assembly is where each room goes
const roomTemplates = {
    " ": {
        bitmap: [
            "          ",
            "          ",
            "          ",
            "          ",
            "          ",
            "          ",
            "          ",
            "          ",
            "          ",
            "          ",
        ],
    }, // An empty room for the " " character.
    A: {
        bitmap: [
            "#########################################",
            "#@@@@@@@@@@@@@@@@@@@@@@@@@@      @@@@@@@#",
            "#@@@@@@@@         @@@@@@@         @@@@@@@",
            "#@@@@@@@           @@@@@@           @@@@@",
            "#@@@@@@@           @@@@@@           @@@@@",
            "#@@@@@@@           @@@@@           @@@@@@",
            "#@@@@@@@           @@@@@          #######",
            "#@@@@@@@           @@@@@    ###     #####",
            "##@@@@@@@@        @@@@###            ####",
            "##@@@@@@@@@  ######@@@@@@            ####",
            "###@@@@@@@@  ######@@@@@@            ####",
            "###@@@@@@@@@########@@@@@            ####",
            "####@@   @@@########@@@@@@          #####",
            "####@     @##########@@@@@@@@@     ######",
            "#####     @##############################",
            "#########################################",
            "#########################################",
            "#########################################",
        ],  
        entities: {
            '1': (x, y) => new MPowerPillar(x, y - 1.8, 'ball'),
            '2': (x, y) => new MPowerPillar(x, y - 1.8, 'groundedTeleport'),
            '3': (x, y) => new MPowerPillar(x, y - 1.8, 'groundPound'),
            '4': (x, y) => new MPowerPillar(x, y - 1.8, 'fullTeleport'),
            'H': (x, y) => new MPothead(x, y),
            'Y': (x, y) => new MMimic(x, y - 0.3), // why is this Y? ftlogidk
            'M': (x, y) => new MMinitaur(x, y - 0.3),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'N': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "nl changed this line lol",
                "he probably wont change it back",
                "while typing this",
                "he noticed it was predicting his text",
                "this is really weird lol",
            ], 'pakala'),
            'K': (x, y) => new MNPC(x, y - 0.6, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'kili'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'sign'),
            'W': (x, y) => new MBreakWall(x, y, 'brickBreakWall', 'right'),
            // 'V': (x, y) => new MBreakWall(x, y, 'grassyBreakWall', 'right'),
            // 'U': (x, y) => new MBreakWall(x, y, 'mushroomBreakWall','right'),
        },
    },
    B: {
        bitmap: [
            "################################",
            "#@     @@@@@@   @@@@@@@@@@######",
            "@@@@    @@@       @@@@@@@@@@@@@@",
            "@@@@@                @@@@@@@@@@@",
            "@@@@@                    @@@@@@@",
            "@@@@@                   ########",
            "###@@@@                    #####",
            "###@@@@             ###     ####",
            "#####@@@@                   ####",
            "#####@@@@       ###         @###",
            "#######@@@@               @@@###",       
            "#######@@@@ ###        @@@@@@###",
            "#########@@@@    @@@@@@@@@@@@###",
            "#########@@@@@@@@@@@@@@@@@@@####",
            "################################",
            "################################",
            "################################",
            "################################",
        ],
        entities: {
            'T': (x, y) => new MNPC(x, y - 0.5, [
                "Hey there traveler.",
                "Name's Tomo.",
                "Watch out for the",
                "crystal spikes...",
            ], 'tomo'),
            'L': (x, y) => new MNPC(x, y - 0.5, [
                "I've been here",
                "a long time.",
                "Too long.",
            ], 'lupa'),
            'K': (x, y) => new MNPC(x, y - 0.5, [
                "Don't touch me.",
            ], 'kasi'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "-> Warning: Danger ahead",
            ], 'sign'),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            //TODO
            //'P': (x, y) => new MEyecrawler?.(x, y),
            //'M': (x, y) => new MMimic?.(x, y),
        },
    },
    C: {
        bitmap: [
            "######################     #######",
            "######################     #######",
            "@@@@###################     ######",
            "@@@@@   @@@@@@@             W  @@@",
            "@@@@@   @@@@            ##     @@@",
            "###@@@@ @@@@                    @@",
            "######@@@@@@@               ######",
            "######@@@@@###########      ######",
            "#######@@@@@@#######   @@@@#######",
            "#########@@@@@###     @@##########",
            "###@@@@@@@@@@@###@@@@@@@@@@@@@@###",
            "##@@@   @@@###########@@@@   @@@##",
            "##@@@   @@@##@@@@@@@@####### @@@##",
            "##@@@   @@###@@@@@@@@@@@@@   @@@##",
            "###@@@@@@@###@@@@@@@@@@@@@@@@@####",
            "#############@@@@@@@@#############",
            "###############@@@################",
            "###############@@@@###############",
        ],
        entities: {
            'W': (x, y) => new MBreakWall(x, y, 'brickBreakWall', 'right'),
        },
    },
    D: {
        bitmap: [
            "###############    #######",
            "##         ##        #####",
            "#          ##        #####",
            "#          ##        #####",
            "#         @##@      @#####",
            "#         @##@@    @@#####",
            "#    C    @@#@@@@@@@@#####",
            "#   #### @@@@@@@@@@@@#####",
            "#   ####@@@@@@@@@@@@@#####",
            "#   #####@@@@@@@@@@@@#####",
            "#   #####@@@@@@@@@@@@#####",
            "#  @##########@@@@@@######",
            "#  @######################",
            "# @@@@@@@@@@@@##@@#@@@@@#@",
            "#@@@@@@@@@@@@@@@@@@@@@@@@@",
            "##@@@###@@@#@@@@@@@@@##@@@",
            "##########################",
            "##########################",
            "##########################",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3),
        },
    },
    E: {
        bitmap: [
            "##########################",
            "##@@@@@@@@       @@@@@@###",
            "#@@@@@              @@@@##",
            "#@@@@                 @@##",
            "#@@@@                  @##",
            "#@@@@                  @##",
            "#@@@@                 @###",
            "#@@@@@@             ######",
            "#@@@@@@@             @@@@@",
            "#@@@@@@#######       @@@@@",
            "#@@@@@@@####         @@@@@",
            "####@@@@###@    ####@@@@@@",
            "##@@@@@@###@@      @@@@@@@",
            "@@@@@@@####@@     @@@@@###",
            "@@@@@@@####@@@ M @@@@@####",
            "@@@@@@######@@   @@@@#####",
            "##########################",
            "##########################",
            "##########################",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'M': (x, y) => new MMinitaur(x, y),
        },
    },
    F: {
        bitmap: [
            "############################################",
            "#@@@@@             @@@@@@@@####@@@@@@@@@####",
            "#@@@@@          @@@@@@@@@@@####@@@@@@@@@####",
            "#@@@             @@@@@@@##########@@@@@@####",
            "#@@            @@@@@@@@    #### @@@@@@@@####",
            "#@@@M      ##########@     ####   @@@#######",
            "##@@@ #       #####@@@     ####             ",
            "#########     ####@@@      #####            ",
            "######        ####@@@   M  ####             ",
            "@@@@##     #######@@@@     ####             ",
            "@@@@##        ####@@@@@@@@ ####         ####",
            "@@@@#####     ####@@@@@@@@@#######     #####",
            "@@@@          ####@@@@@@@@@@@         ######",
            "##@@@@    ########@@@@@@@@@@@@@@     #######",
            "##################@@@@@@@@@#################",
            "############################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        },
    },
    G: {
        bitmap: [
            "#################",
            "##@@@@@@@@@@@@@##",
            "#@@@@@     @@@@@#",
            "#@@@@       @@@@#",
            "####         ####",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "####         ####",
            "#@      1      @#",
            "#@@@  #####  @@@#",
            "#@@@@@#####@@@@@#",
            "#@@@@#######@@@@#",
            "#@@@@#######@@@@#",
            "#################",
        ],
        entities: {
            '1': (x, y) => new MPowerPillar(x - 0.5, y - 1.8, "ball"),
        },
    },
    H: {
        bitmap: [
            "##########@@@@###",
            "##########@@@@@##",
            "###########@@@@@#",
            "###########@@@@@#",
            "##       @##@@@@#",
            "         @##@@@@#",
            "        @@@##@@@#",
            "      @@@@@##@@@#",
            "     @@@@@@@@@@##",
            "     @@@@@@@@@@##",
            "## @@@###########",
            "##@@#############",
            
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        },
    },
    I: {
        bitmap: [
            "################",
            "################",
            "################",
            "################",
            "#####         ##",
            "##            ##",
            "#            @##",
            "#            @##",
            "#         @  @##",
            "#         @  @##",
            "#         @@ @##",
            "          @@@@##",
            "         @@@@@##",
            "        @@@@@@##",
            "    C @@@@@@@@##",
            "##########@@@@##",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3), 
            'Y': (x, y) => new MMimic(x, y - 0.3),
            'F': (x, y) => new MFlyer(x, y),
            'Q': (x, y) => new MSwarmer(x, y, 5),
        },
    },
    J: {
        bitmap: [
            "########################",
            "########################",
            "########################",
            "########################",
            "##        @@@@@@@@@@@###",
            "#              @@@@M@@##",
            "#                @@@@@##",
            "#                 ######",
            "                     ###",
            "        @@@@          ##",
            "     @@@@@####        ##",
            "   @@@@ @@##@@          ",
            "# @@@@@@@###@@@@###     ",
            "##@@@M@@@###@@@@@       ",
            "##@@@@@@######@@@       ",
            "########################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        },
    },
    K: {
        bitmap: [
            "####################################################",
            "######          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##",
            "@@@                    @@@@@@@@@@@       @@@@@@@@@@#",
            "@@@                    @@@@@@@@@            @@@@@@@#",
            "@@@@                    @@@@@@@@              @@@@@#",
            "########    ##            @@@@@               @@@@@#",
            "######      ######                             @@@@#",
            "###### @@@@   ####                                 #",
            "######@@@@@@@ #####                                 ",
            "######@@@@@ @@#####                                 ",
            "######@@@@@@@@######    ####                        ",
            "######@ @@@@@#######                                ",
            "######@@@@@@@@@                ####             ####",
            "######@@@@@@@@@@@      @@@@@@@#####             ####",
            "######@@M@@@@@@@@@@@@@@@@M@@@@######    M      #####",
            "######@@@@@###########@@@@@@@#######           #####",
            "####################################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
            'R': (x, y) => new MBlob(x, y, "r2"),
        },
    },
    L: {
        bitmap: [
            "######################################",
            "#@         @@@@@@@@@@@@@@@@         @#",
            "@@            @@@@@@@@@@            @@",
            "@@@             @@@@@@             @@@",
            "@@@              @@@@            ##@@@",
            "#####  M                      M  #####",
            "##@@##    ##              ##    ##@@##",
            "#@@@########              ########@@@#",
            "#@@@@######    ## N  ##    ######@@@@#",
            "#@@@@@@@@     ##########     @@@@@@@@#",
            "#@@@@@@@@@@@@@##########@@@@@@@@@@@@@#",
            "#@@@@@@@@@@@@############@@@@@@@@@ @@#",
            "#@@@@@@@@@@@@############@@@@@@@@@@@@#",
            "#@@@@@@M@@@@##############@@@@M@@@@@@#",
            "##@@@@@@@@@################@@@@@@@@@##",
            "######################################",
            "######################################",
            "######################################",
            "######################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
            'N': (x, y) => new MNPC(x + 0.2, y - 0.5, [
                "Normally,",
                "This room would be a gauntlet.",
                "The doors at either side would close.",
                "And you'd have to beat up the badguys.",
                "But nobody implemented that yet...",
                "...so you get me, instead.",
                "*Hef, hef, horf!*",
            ], "pakala"),
        }
    },
    M: {
        bitmap: [
            "################",
            "#####@@@@@@@@###",
            "####@@    @@####",
            "###        @@@##",
            "#    @@        #",
            "#@            ##",
            "#@    H  @      ",
            "#@@@            ",
            "###@@@      ####",
            "################",
            "################",
        ],
        entities: {
            'H': (x, y) => new MHatPoint(x, y),
        }
    },
    N: {
        bitmap: [
            "##@@##################################",
            "#@@@@@                 ###############",
            "#@@@@@@@@              ###############",
            "###############         ##############",
            "################           @@@@@@@####",
            "################               @@@@###",
            "       @@@@@#######               @@@#",
            "           @@@##            @@@@   @@#",
            "###          @@#     ###  @@@@ @@@  @#",
            "#              #          @@@@@@@@@ @#",
            "#@   ##   @@   #         @###@ @@@@@@#",
            "#@             #         @@@@ @@@@@  #",
            "#@    @ ##  @@ #          @@@@@###@@@#",
            "#@@            #        @@@@@@@@@@ @@#",
            "#@@@@        ###         @@@@@@@@@@ ##",
            "#@ @@       ####   M    @@@ @@@@@@@@##",
            "#@@@@    #######         @@@  @@@@####",
            "##@ @@@@              @@@@@@@@@#######",
            "######@@@@@     @@@@@@@@@@@@##########",
            "######################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        }
    },
    O: {
        bitmap: [
            "BBBBBBBBBBBBBB####################",
            "BBBBBBBBBBBBB#####################",
            "BBBBBBB###########################",
            "bbbbbbb            ###############",
            "bbbbbb             ###############",
            "bbbbbb  b            #############",
            "bbbbbbbbb            #############",
            "bbbbbbbb               ###########",
            "bbbbbbbb   bbbb        ###########",
            "BBbbbbbbbbbb             #########",
            "BBbbbbbbbbb              #########",
            "BBBBbbbbbb                 #######",
            "##BBbbbbbb  b              #######",
            "###BBBbbbbbbb              #######",
            "####BBbbbbbb               #######",
            "######BBBbbbb              #######",
            "########BBBbbb C           #######",
            "######################     #######",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3),
        },
    },
    P: {
        bitmap: [
            "BBbbbbbbBBBBBBBBBBBBBB",
            "B   bbbbbbbbbbbBBBBBBB",
            "B   BBBbbbbbbbbbBBBBBB",
            "B         bbbbbbbbbbbb",
            "BB       bb   bbbbbbbb",
            "BB             bbbbbbb",
            "BBBB           bbbbbbb",
            "BBbb  BBBB    bbbbbbbb",
            "Bbb   BBB   BBBB bbbbb",
            "BBbb        BBB    BBB",
            "BBbbbbb            BBB",
            "BBbbbbbbb b       BBBB",
            "BBbbbbbbbbb       BBB#",
            "BBbbbbbbbb     E BBB##",
            "BBbbbbbbbbbbb    BB###",
            "#BBbbbbbbbbb  ########",
            "#####bbbb#############",
            "######################",
            "######################",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
        },
    },
    Q: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
            "BBBBBBBBBBB BBBBBBBBBBbbbbBBBBBBBBB",
            "BBBBBBBBB    BBBBBBBBBbbbbbbBBBBBBB",
            "BBBbbbb             bbbbbbbbbbbbbbb",
            "BBbbb bbb              bbbbbbbbbbbb",
            "BBbbb                  bBBBBBBBBBBB",
            "BBbbb                  BBBBBBBBBBBB",
            "BBbb                  BBBbBBBbbBBBB",
            "Bbbbbb               EBBbbBbBbbbBBB",
            "Bbbbb       BB    BBbbbbbbbbBbbbbbb",
            "bbbbbbb    BBBBBBBBBBbbbbbbbbbbbbbb",
            "bbbbbbbbbb BBBBBBBBBBBbbbbbbbbbbBBB",
            "bbbbbbbbbbBBBBBBBBBBBBBbbbbbbbbBBBB",
            "BbbbbbbbbbBBBBBBBBBBBBBbbbbbbbbBBBB",
            "BBbbbbbbBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
        },
    },
    R: {
        bitmap: [
            "BBBBBBBBBBBBBBBBB",
            "bbbbbBBBBBBBBBBBB",
            "bbbbbbBBBBBBBBBBB",
            "bbbbbbbbbbbbbBBBB",
            "bbbbbbbbbbbbbbBBB",
            "bbbbbbbbbbbbbbBBB",
            "bbbbbbbbbbbbbbBBB",
            "BBBbbbbbbbbbbbBBB",
            "BBbbbbbbbbbbbBBBB",
            "BBbbbBBBBBBBBBBBB",
            "BBbbbb     bbbBBB",
            "BBBbbbb     bbBBB",
            "BBBbb b     bbbBB",
            "BBBBB        bbbb",
            "BBBBBBB    bbbbbb",
            "BBBbbb  bbbbbbbbb",
            "BBBbbbbbBBBBbbbBB",
            "BBBBBBBBBBBBBBBBB",

        ],
        entities: {

        },
    },
    S: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBB      ",
            "BBBBBBBBBB     BBBBBB        ",
            "BBBBBBBBBBB     BB           ",
            "BBBBbbbbbb       BB          ",
            "BBBBBbb                      ",
            "BBbbbbbbb                    ",
            "bbbbbb  bbb                  ",
            "bbbbbb                       ",
            "Bbbbbbbbbb       BBBBBB      ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBB   BBBBBBBBBBBBBBBBBBB",
            "bbbBBb     BBBBBBBBBBBBBBBBBB",
            "bbbbb   H  BBBBBBBBBBBBBBBBBB",
            "BBbbbbb    BBBBBBBBBBBBBBBBBB",
            "BBBBBb    BBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'H': (x, y) => new MHatPoint(x, y),
        },
    },
    T: {
        bitmap: [
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "BBBBBB                                      ",
            "BBBBBBBBBBB                                 ",
            "BBBBBBBBBBBBBBB          BBBBBBBBB          ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB      ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {

        },
    },
    U: {
        bitmap: [
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                        BBBBB       ",
            "                      BBBBBbbbb     ",
            "            S       BBBBBBBbbbbBB   ",
            "         BBBBBBBBBBBBBBBBBBBbbbBBB  ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",

        ],
        entities: {
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "Awen Outpost\n->",
                "West Castle Tower\n<-",
            ], 'sign'),
        },
    },
    V: {
        bitmap: [
            "                                      ",
            "                                      ",
            "                                      ",
            "                                      ",
            "                               $BB    ",
            "                      p         BBB   ",
            "                    C BBBBBBBBBBBBBBBB",
            "               P BBBbbBBBbbbbBBBBBBBBB",
            "         BBBBBbbbBBbbbbbbbbbbbbbBBBBBB",
            "     BBBBBBBbbbbbBBbbbbbbbbbbbbbbbbBBB",
            "    BBBBBBBbbbbbBBbbbbbbbbbbbbbbbbbbBB",
            "   BBBBBBBBbbbbBBBbbbbbbbbbbbbbbbbbbBB",
            " BBBBBBBBBBbbbBBbbbbbbbbbbbbbbbbbbbbBB",
            "BBBBBBBBBBBBbbbbbbbbbbbbBBBBBBBBBbbbBB",
            "BBBBBBBBBBBBbbbbbbbbbbbbbbBBBBbbbbbbBB",
            "BBBBBBBBBBBBBbbbbbbbbbbbbbbBBbbbbbbBBB",
            "BBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbbbbBBB",
            "BBBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbbBBBB",
            "BBBBBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbBBBB",
            "BBBBBBBBBBBBBBBBBBBbbbbbbbbbbbBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'p': (x, y) => new MNPC(x + 0.5, y + 13.5, [
                "Normally, there'd be a buncha NPCs down here...",
                "To give you advice and sell stuff.",
                "But nobody implemented that yet...",
                "...so you get...",
                "...Me.",
                "Instead.",
                "I know you're reading this, Arrow.",
                "*Hef, hef, horf!*",
            ], 'pakala'),
            '$': (x, y) => new MHatShop(x, y + 13),
            'C': (x, y) => new MCheckpoint(x, y + 10),
        }, // Lotsa NPCs for this one. :)
    },
    W: {
        bitmap: [
            "                              ############@@@@@@############",
            "                              ###########@@@@@@@@###########",
            "                            ############@@@@##@@@@##########",
            "                            ###########@@@@####@@@@#########",
            "                          ############@@@@######@@@@########",
            "  S      BB      E     BBB###########@@@@########@@@@#######",
            "BBBBBBBBBBB          BBB############@@@@##########@@@@######",
            "BBBBBBBBBBBBBBBBBBBBBBBB###########@@@@############@@@@#####",
            "BBBBBBBBBBBBBBBBBBBBBB############@@@@##@@@@@@@@@@##@@@@####",
            "BBBBBBBBBBBBBBBBBBBBBB###########@@@@##@@@@@@@@@@@@##@@@@###",
            "BBBBBBBBBBBBBBBBBBBB############@@@@##@@@@@@@@@@@@@@##@@@@##",
            "BBBBBBBBBBBBBBBBBBBB############@@@##@@@@###@@###@@@@##@@@##",
            "BBBBBBBBBBBBBBBBBBBB###########@@@##@@@@@@##@@##@@@@@@##@@@#",
            "BBBBBBBBBBBBBBBBBB#############@@##@@@@@@@##@@##@@@@@@@##@@#",
            "BBBBBBBBBBBBBBBBBB#############@@@@@@@@@@@##@@##@@@@@@@@@@@#",
            "BBBBBBBBBBBBBBBB################@@@@@@@@@@##@@##@@@@@@@@@@##",
            "BBBBBBBBBBBBBBBB############################@@##############",
            "BBBBBBBBBBBBBB##############################@@##############",
            "BBBBBBBBBBBBBB#######################@@@@@@@@@##############",
            "BBBBBBBBBBBBBB#######################@@@@@@@@@##############",
            "BBBBBBBBBBBBBB#######################@@#####################",
        ],
        entities: {
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "Awen Outpost\n<-",
                "Central Castle Tower\n->",
            ], 'sign'),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
        },
    },
    X: {
        bitmap: [
            "                                                            ",
            "                                    ##  ##  ##  ##  ##      ",
            "                                    ##  ## C##  ##  ##      ",
            "                                    ##################      ",
            "                                    ##################      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    @@@@@@@@@@@@@@@@@@      ",
            "                                    @@@@@@@@@@@@@@@@@@      ",
            "                                    @@@@@@@@@@@@@@@@@@      ",
            "                                  ####@@@########@@@####BB  ",
            "                                  #####@@@######@@@#####BBBB",
            "                                ########@@@@@@@@@@########BB",
            "                                #########@@@@@@@@#########BB",
            "                              ############@@@@@@############",
        ],
        entities: {
            "C": (x, y) => new MCheckpoint(x + 1, y + 8),
        },
    },
    Y: {
        bitmap: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "               eE           ",
            "       bbBBBBBBbbb          ",
            "    BBbbbbbbbbbbbbBBB       ",
            "   BBBbbbbbbbbbbbbbBBBBBBBBB",
            "BBBBBBBbbbbbbbbbbbbBBBBBBBBB",
            "BBBBBBBBBbbbbbbbbbBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "WARNING",
                "Chasm ahead.",
                "To avoid falling, excercise caution.",
                "Central Castle Tower <-",
            ], "sign"),
        },
    },
    Z: {
        bitmap: [
            "BB    BBBBBBBBBBBB",
            "BB     BBBBbbbbbbb",
            "BBB    BBBbbbbbbbb",
            "BB     BBB bbbbbbb",
            "BB    BBBB  bbbbbb",
            "BB     BBB    bbbb",
            "BBB    BBB     bbb",
            "BBbbbb BBBB###BBBB",
            "BBbbbbBBBB  S BBBB",
            "BBbbbbb          B",
            "BBBbbbbbbb       B",
            "BBBBBBBBBBBBB    B",
            "BBBBBBBBBBB      B",
            "BBBBBBBBBBB    BBB",
            "BBBBBBBBBBB      B",
            "BBBBBBBBBBBBB    B",
        ],
        entities: {
            "S": (x, y) => new MNPC(x - 0.3, y - 2.5, [
                "There should be...",
                "A ground pound floor here."
            ], "sign"),
        },
    },
    a: {
        bitmap: [
            "",
            "",
            "",
            "                                   ",
            "                            BBBBB  ",
            "                            BBBBB  ",
            "                             BBB   ",
            "                                   ",
            "                                   ",
            "            e                      ",
            "          bbbbb                    ",
            "      BBBbbbbbbbBBbbb  BB          ",
            "      BBBBbbbbbbBBBBbbbbb     S    ",
            "     BBBBBbbbbBBBBBBbbbbbbbBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBbbbbBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBbbbbbbbBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBbbbbbbbBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBbbbbBBBBBBB",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "Central Castle Tower\n<-",
                "Shroom Field\n->"
            ], "sign"),
        },
    },
    b: {
        bitmap: [
            "                bbbbbbbbBBBB",
            "                  bbbbbbBBBB",
            "                   ebbbBBBBB",
            "   bbb         BBbbbbbBBBBBB",
            " BBBBbbbbb   BBBBBBBBBBBBBBB",
            " BBBbbbbbbbb   bbbbbBBBBBBBB",
            "  bbbbbBBBBbbbbbbbbbbBBBBBBB",
            "     bbbBBBbbbbbbbbbbBBBBBBB",
            "       bbbbbbBBBBbbbbBBBBBBB",
            "        bbbbbBBBbbbBBBBBBBBB",
            "        ebbbbbbbbbbBBBBBBBBB",
            "        bbbbbbbbbbBBBBBBBBBB",
            "   BBBBbbbbbbbbbBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            e: (x, y) => new MBlob(x, y, "g1"),
        },
    },
    c: {
        bitmap: [
            "",
            "",
            "",
            "                               ",
            "                     BBBBB     ",
            "                  BBBBBBBBBBB  ",
            "                 BBBBBBBBBBBBBB",
            "               BBBbbbbbBBBBBBBB",
            "              bBBbbbbbbbBBBBBBB",
            "          BBBbbbbbbbbbbbBBBBBBB",
            "          BBbbbbbbbbbbbbbBBBBBB",
            "             bBBBbbbbbbbbBBBBBB",
            "              BBbbbbbbbbbBBBBBB",
            "               bbbbBBBbbbBBBBBB",
            "               bbbbBBbbbbBBBBBB",
            "               bbbbbbbbbBBBBBBB",
        ],
        entities: {

        },
    },
    d: {
        bitmap: [
            "                   ^",
            "                   ^",
            "                   ^",
            "                    ",
            "                    ",
            "                    ",
            "BB                  ",
            "BBB                 ",
            "BBB                 ",
            "BBBB                ",
            "BBBB            ^^^ ",
            "BBBBBB           ^^ ",
            "BBBBBB     ^^^      ",
            "BBBBBBB     ^^      ",
            "BBBBBBB             ",
            "BBBBBBBB            ",
        ],
        entities: {

        },
    },
    e: {
        bitmap: [
            "BBBBBBBB                ",
            "BBBBBBBB                ",
            "BBBBBBBB                ",
            "BBBBBBBB                ",
            "BBBBBBBBB               ",
            "BBBBBBBBB               ",
            "BBBBBBBBB               ",
            "BBBBBBBBB             bb",
            "BBBBBBBBB            bbb",
            "BBBBBBBBB            bbb",
            "BBBBBBBBB          M bbb",
            "BBBBBBBBBB          bbbb",
            "BBBBBBBBBB^^^      bbbbb",
            "BBBBBBBBBB^^^^^^^^^^^^^^",
            "BBBBBBBBBB^^^^^^^^^^^^^^",
            "BBBBBBBBBBB^^^^^^^^^^^^^",
        ],
        entities: {
            'M': (x, y) => new MFlyer(x, y),
        },
    },
    f: {
        bitmap: [
            "                                ",
            "                                ",
            "                                ",
            "                                ",
            "               C                ",
            "             bbbbbb             ",
            "            bbbbbbbb            ",
            "bbb   M     bbbbbbbb    M    bbb",
            "bbbb        bbbbbbbb        bbbb",
            "bbbb        bb^^^^bb        bbbb",
            "bbbbb      bbbbbbbbbb      bbbbb",
            "bbbbbbbbb^^^^bbbbbb^^^^bbbbbbbbb",
            "bbbbbbbb^^^^^^^^^^^^^^^^bbbbbbbb",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^^^^^^^^^##^^^^^^^^##^^^^^^^^^^",
            "^^^^^^^^################^^^^^^^^",
        ],
        entities: {
            'M': (x, y) => new MFlyer(x, y),
        },
    },
    g: {
        bitmap: [
            "^                      ^  ^",
            "^                      ^  ^",
            "^                      ^ ^^",
            "                    ^  ^  ^",
            "                    ^^ ^  ^",
            "                     ^^^^ ^",
            "       ^^              ^  ^",
            "       ^^       H      ^  ^",
            " ^^^   ^^              ^  ^",
            "  ^^   ^^^^^^^     ^^^^^  ^",
            "        ^^^^^^^   ^^^^^  ^^",
            "             ^^   ^^      ^",
            "             ^^   ^^      ^",
            "              ^   ^       ^",
            "                           ",
            "",
            "",
        ],
        entities: {
            "H": (x, y) => new MHatPoint(x, y),
        },
    },
    h: {
        bitmap: [
            "   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   ^^^^",
            "   ^^^^^bbbbbbbbbbbbbbbbbbbbbbbb     ^^^^",
            "   ^^^^bbbbbbbbbbbbbbbbbbbbbbbb    ^^^^^^",
            "   ^^^^bbW^^^^^^^^^^^^^^^^^^^^b    ^^^^^^",
            "   ^^^^bbbbbbb^^^^^^^^^^^^^^^^b   ^^^^^^^",
            "   ^^^^^bbbbbb^^bbbbbbbbbbbb^^^   ^^^^^^^",
            "   ^^^^^^^^^bb^bbbbbbbbbbbbbb^^^   ^^^^^^",
            "   ^^^        ^bbbbbbbbbbbbbb^^^   ^^^^^^",
            "   ^^^       ^^bbbbbbbbbbbbbbb^^^    ^^^^",
            "   ^^^  ^^^^^^^bbb^^^^bbbb    ^^^    ^^^^",
            "   ^^^  ^ e    bbb^^^bbbbb     ^^^   ^^^^",
            "             bbb^^^^                 ^^^^",
            "            ^^^^^^^^                ^^^^#",
            "^^^^^^^^^^^^^^^^^^^^     C       ^^^^^^##",
            "^^^^^^^^^########^^^^^^^^^^^^^^^^^^^^####",
            "^^^^^^############^^^^^^^^^^^^^^^^^^#####",
        ],
        entities: {
            'M': (x, y) => new MFlyer(x, y),
            "C": (x, y) => new MCheckpoint(x, y - 3),
            "W": (x, y) => new MBreakWall(x, y, "mushroomBreakWall", "right"),
        },
    },
    i: {
        bitmap: [
            "^^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^^bbb^^^            bbbbbbbbbbbb^^^^^^^^^",
            "^^^bbb^^               Hbbbbbbbbb^^^^^^^^^",
            "^^^bbb^^                 bbbbbbbb^^^^^^^^^",
            "^^^bbb^^                 bbbb^^^^^^^^^^^^^",
            "^^^bbb^^                 bbbb^^^^^^^^^^^^^",
            "^^^bbb^^b       1         bbb^^^^^^bbbbb^^",
            "^^^bbb^bbbb ^^^^^^^^         ^^^^^bbbbbbb^",
            "^^^bbb^bbbb^^^^^^^^^^        ^^^^^bbbbbbb^",
            "^^^bbbbbbbb^^^^^^^^^^        ^^^^^bbbbbbb^",
            "^^^bbbbbbb^^^^^^^^^^^^       ^^^^   bbbbb^",
            "^^^bbbbbbb^^^^^^^^^^^^               bbbb^",
            "^^^^bbbbb^^^^^^^^^^^^^^               bb^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^         ^^^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   ^^^^^",
        ],
        entities: {
            '1': (x, y) => new MPowerPillar(x - 1, y - 1.8, "wallJump"),
            "H": (x, y) => new MHatPoint(x + 8, y)
        },
    },
    j: {
        bitmap: [
            "^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^bbbbbbbbbbbbb         bbbbb^^^^^^^^^^^^^",
            "^^bbbbbbbbbbbbb    F     bbbb^^^^^^^^^^^^^",
            "^^bbbbbbbbbbbb^^^        bbbbbbb^^bbbb  ^^",
            "^^bbbbbbbbbbb^^^^          bbbbb^^bb    ^^",
            "^^^bbbbbbbbbb^^^^    ^^^^^^^^^^b^^b^^   ^^",
            "^^^^^^^^^^^^^^^^^     ^^^^^^^^^bbbb^^   ^^",
            "^^^^^^^^^^^^^^^^             ^^bbbb^^   ^^",
            "^^^^^^^^^^^^^^               ^^    ^^   ^^",
            "^^^^^^^^^^^^^         F      ^^    ^^   ^^",
            "^^^bbbb^^^^^^                           ^^",
            "^^bbbbbb^^^^^                           ^^",
            "^^bbbbbbb^^^                            ^^",
            "^^bbbbbbbbb     ^^^^^^^^^              ^^^",
            "^^bbbbbbbbb  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        ],
        entities: {
            'S': (x, y) => new MSwarmer(x, y),
            'F': (x, y) => new MFlyer(x, y),
        },
    },
    k: {
        bitmap: [
            "^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^bbbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^^",
            "^^bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^",
            "^^bbbbbbbbbbbbbbbbbbbb^^^bbbbbbbbbbbbbb^^^",
            "^^^^^^^bbbbbbbbbbbbbbb^^^bbbbbbbbbbbbbb^^^",
            "^^^^^^^^bbb^^^^^^^bbbb^^^bbbb^^^^^^^bbb^^^",
            "^^^^^^^^bbbbb   bbbbbb^^^bbbbbb   bbbbb^^^",
            "^^^^^^^^bbbbb S bbbbbb^^^bbbbbb S bbbbb^^^",
            "^^^^^^^^bbbbb   bbbbbb^^^bbbbbb   bbbbb^^^",
            "^^^^^^^bbbbbbbbbbbbbbb^^^bbbbbbbbbbbbbb^^^",
            "^^bbbbbbbbbbbbbbbbbbbb^^^bbbbbbbbbbbbbb^^^",
            "^bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^",
            "^bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^",
            "^bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^^",
            "^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        ],
        entities: {
            'S': (x, y) => new MSwarmer(x, y),
            'F': (x, y) => new MFlyer(x, y),
        },
    },
    l: {
        bitmap: [
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^bb^^^^^bbbb^^bb^^^bbb^bbbbbb          ^^^",
            "bbbb^bbbbbbbb^bbbbbbbbbbbbbbbb          ^^",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb          ^^",
            "^^^bbb^^^^^^bbbb^^^^^bbb^^bbbb   ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^b    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^     ^^^    ^^",
            "^^bbbbb                          ^^^    ^^",
            "^bbbbbbb                                ^^",
            "^bbbbbbb                                ^^",
            "^bbbbbbb                               ^^^",
            "^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        ],
    },
    m: {
        bitmap: [
            "             ^^^^^^^^^^^^^^",
            "                  ^^^^^^^^^",
            "                    ^^^bbbb",
            "                    ^^^bbbb",
            "^^^^^^               ^^bb^^",
            "^^                   ^^bbb^",
            "^                    ^^bbb^",
            "^                    ^^^bb^",
            "^                    ^^^bb^",
            "^                     ^^bb^",
            "^                      ^bb^",
        ],
    },
    n: {
        bitmap: [
            "^                      ^bb^",
            "^                      ^bb^",
            "^                      ^bb^",
            "^          H H H       ^b^^",
            "^          ^^^^^       ^bb^",
            "^    ^^^    ^^^        ^bb^",
            "^     ^^               ^^b^",
            "^     ^^               ^bb^",
            "^          ^^^         ^bb^",
            "^         ^^^^         ^bb^",
            "^         ^^^   ^^^    ^bb^",
            "^         ^^^    ^^    ^bb^",
            "^         ^^^          ^bb^",
        ],
        entities: {
            "H": (x, y) => new MHatPoint(x, y),
        },
    },
    o: {
        bitmap: [
            "^         ^^^          ^  ^",
            "^         ^            ^  ^",
            "^         ^            ^ ^^",
            "^         ^  ^^    ^^^^^  ^",
            "^         ^  ^        ^^  ^",
            "^         ^^^^         ^^ ^",
            "^          ^^^         ^  ^",
            "^                      ^  ^",
            "^                ^^^   ^  ^",
            "^                 ^^   ^  ^",
            "^                      ^  ^",
        ],
    },
    p: {
        bitmap: [
            "",
            "",
            "",
            "                                   ",
            "        bbbbb          #           ",
            "      bbbbbbbb       @##           ",
            "BBB  bbbbb#b#b# # @@@@##           ",
            "BBBBBBBbbb#######@@@@@##           ",
            "BBBBBBBbbb#######@@@@@#         BBB",
            "BBBBBBBbbb#@@@@@#@@@@bb        BBBB",
            "###BBBBbbb#@@@@@#@@@bbbb       BBBB",
            "###BBBBbb@@@@@@@@@@@bbbb       BBBB",
            "###BBBB@@@@@@@@@@@@@bbbbb      BBBB",
            "####BBBBBB#######BBBbbbbbbbb  BBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
        ],
        entities: {
            "N": (x, y) => new MPothead(x, y),
        },
    },
    q: {
        bitmap: [
            "",
            "",
            "",
            "                                   ",
            "BBBbbb                             ",
            "BBBBbb                             ",
            "BBBBbbb                       BBBBB",
            "BBBBbbbbbb        bbbbbbb    BBBBBB",
            "BBBBbbbbbbbbb   bbbbbbbbbbb@@###BBB",
            "BBBBbbbbb@@@@@@@@@bbbbbbbb@@@###BBB",
            "BBBBBbbbbbb@@@bbbbbbbbbbb@@@@######",
            "BBBBBBBBB@@@@@@@@@bbbbbbb@@@@######",
            "BBBBBBB####BBBBBBBBbbbbbbb@@@######",
            "BBBBBB####BBBBBBBBBBBBBBBBBB#######",
            "BBBBBB##########BBBBBBBBB##########",
            "BBBB######BBBBBBBBBBBBBBBBB########",
        ],
        entities: {
            "N": (x, y) => new MPothead(x, y),
        },
    },
    r: {
        bitmap : [

        ],
    },
    ℤ: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                  ",
            "B                                  ",
            "B                                  ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            "N": (x, y) => new MPothead(x, y),
        },
    },
    λ: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "                                  B",
            "                                  B",
            "                                  B",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            "N": (x, y) => new MPothead(x, y),
        },
    },
};

const worldAssembly = [
    "ℤλ          ml",
    "            nk",
    "            oj",
    "          cdgi",
    "rqp    XYabefh",
    "ZRQSTUVW",
    "  PO", 
    " ABCLKJI",
    "   DEFGH",
    "      MN",
];

