//each room has a name "A" for instance. World Assembly is where each room goes
const roomTemplates = {
    A: {
        bitmap: [
            "#########################################",
            "#@@@@@@@@@@@@@@@@@@@@@@@@@@      @@@@@@@#",
            "#@@@@@@@@         @@@@@@@         @@@@@@@",
            "#@@@@@@@           @@@@@@           @@@@@",
            "#@@@@@@@           @@@@@@           @@@@@",
            "#@@@@@@@           @@@@@           @@@@@@",
            "#@@@@@@@           @@@@@          #######",
            "#@@@@@@@           @@@@@    ###     #####",
            "##@@@@@@@@        @@@@###            ####",
            "##@@@@@@@@@  ######@@@@@@            ####",
            "###@@@@@@@@  ######@@@@@@            ####",
            "###@@@@@@@@@########@@@@@            ####",
            "####@@   @@@########@@@@@@          #####",
            // "####@  P  @##########@@@@@@@@@     ######",
            "####@     @##########@@@@@@@@@     ######",
            "#####     @##############################",
            "#########################################",
            "#########################################",
            "#########################################",
        ],  
        entities: {
            '1': (x, y) => new MPowerPillar(x, y - 1.8, 'ball'),
            '2': (x, y) => new MPowerPillar(x, y - 1.8, 'groundedTeleport'),
            '3': (x, y) => new MPowerPillar(x, y - 1.8, 'groundPound'),
            '4': (x, y) => new MPowerPillar(x, y - 1.8, 'fullTeleport'),
            'H': (x, y) => new MPothead(x, y),
            '*': (x, y) => new MHatPoint(x, y),
            'Y': (x, y) => new MMimic(x, y - 0.3), // why is this Y? ftlogidk
            'M': (x, y) => new MMinitaur(x, y - 0.3),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'N': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "nl changed this line lol",
                "he probably wont change it back",
                "while typing this",
                "he noticed it was predicting his text",
                "this is really weird lol",
            ], 'pakala'),
            'K': (x, y) => new MNPC(x, y - 0.6, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'kili'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'sign'),
            'W': (x, y) => new MBreakWall(x, y, 'brickBreakWall', 'right'),
            // 'V': (x, y) => new MBreakWall(x, y, 'grassyBreakWall', 'right'),
            // 'U': (x, y) => new MBreakWall(x, y, 'mushroomBreakWall','right'),
        },
        background: "dungeon"
    },
    B: {
        bitmap: [
            "################################",
            "#@     @@@@@@   @@@@@@@@@@######",
            "@@@@    @@@       @@@@@@@@@@@@@@",
            "@@@@@                @@@@@@@@@@@",
            "@@@@@                    @@@@@@@",
            "@@@@@                   ########",
            "###@@@@                    #####",
            "###@@@@             ###     ####",
            "#####@@@@                   ####",
            "#####@@@@       ###         @###",
            "#######@@@@               @@@###",       
            "#######@@@@ ###        @@@@@@###",
            "#########@@@@    @@@@@@@@@@@@###",
            "#########@@@@@@@@@@@@@@@@@@@####",
            "################################",
            "################################",
            "################################",
            "################################",
        ],
        entities: {
            'T': (x, y) => new MNPC(x, y - 0.5, [
                "Hey there traveler.",
                "Name's Tomo.",
                "Watch out for the",
                "crystal spikes...",
            ], 'tomo'),
            'L': (x, y) => new MNPC(x, y - 0.5, [
                "I've been here",
                "a long time.",
                "Too long.",
            ], 'lupa'),
            'K': (x, y) => new MNPC(x, y - 0.5, [
                "Don't touch me.",
            ], 'kasi'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "-> Warning: Danger ahead",
            ], 'sign'),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            //TODO
            //'P': (x, y) => new MEyecrawler?.(x, y),
            //'M': (x, y) => new MMimic?.(x, y),
        },
        background: "dungeon"
    },
    C: {
        bitmap: [
            "######################     #######",
            "######################     #######",
            "@@@@###################     ######",
            "@@@@@   @@@@@@@             W  @@@",
            "@@@@@   @@@@            ##     @@@",
            "###@@@@ @@@@                    @#",
            "######@@@@@@@               ######",
            "######@@@@@###########      ######",
            "#######@@@@@@#######   @@@@#######",
            "#########@@@@@###     @@##########",
            "###@@@@@@@@@@@###@@@@@@@@@@@@@@###",
            "##@@@   @@@###########@@@@   @@@##",
            "##@@@   @@@##@@@@@@@@####### @@@##",
            "##@@@   @@###@@@@@@@@@@@@@   @@@##",
            "###@@@@@@@###@@@@@@@@@@@@@@@@@####",
            "#############@@@@@@@@#############",
            "###############@@@################",
            "###############@@@@###############",
        ],
        entities: {
            'W': (x, y) => new MBreakWall(x, y, 'brickBreakWall', 'right'),
        },
        background: "dungeon"
    },
    D: {
        bitmap: [
            "###############    #######",
            "##         ##        #####",
            "#          ##        #####",
            "#          ##        #####",
            "#         @##@      @#####",
            "#         @##@@    @@#####",
            "#    C    @@#@@@@@@@@#####",
            "#   #### @@@@@@@@@@@@#####",
            "#   ####@@@@@@@@@@@@@#####",
            "#   #####@@@@@@@@@@@@#####",
            "#   #####@@@@@@@@@@@@#####",
            "#  @##########@@@@@@######",
            "#  @######################",
            "# @@@@@@@@@@@@##@@#@@@@@#@",
            "#@@@@@@@@@@@@@@@@@@@@@@@@@",
            "##@@@###@@@#@@@@@@@@@##@@@",
            "##########################",
            "##########################",
            "##########################",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3),
        },
        background: "dungeon"
    },
    E: {
        bitmap: [
            "##########################",
            "##@@@@@@@@       @@@@@@###",
            "#@@@@@              @@@@##",
            "#@@@@                 @@##",
            "#@@@@                  @##",
            "#@@@@                  @##",
            "#@@@@                 @###",
            "#@@@@@@             ######",
            "#@@@@@@@             @@@@@",
            "#@@@@@@#######       @@@@@",
            "#@@@@@@@####         @@@@@",
            "####@@@@###@    ####@@@@@@",
            "##@@@@@@###@@      @@@@@@@",
            "@@@@@@@####@@     @@@@@###",
            "@@@@@@@####@@@ M @@@@@####",
            "@@@@@@######@@   @@@@#####",
            "##########################",
            "##########################",
            "##########################",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'M': (x, y) => new MMinitaur(x, y),
        },
        background: "dungeon"
    },
    F: {
        bitmap: [
            "############################################",
            "#@@@@@             @@@@@@@@####@@@@@@@@@####",
            "#@@@@@          @@@@@@@@@@@####@@@@@@@@@####",
            "#@@@             @@@@@@@##########@@@@@@####",
            "#@@            @@@@@@@@    #### @@@@@@@@####",
            "#@@@M      ##########@     ####   @@@#######",
            "##@@@ #       #####@@@     ####             ",
            "#########     ####@@@      #####            ",
            "######        ####@@@   M  ####             ",
            "@@@@##     #######@@@@     ####             ",
            "@@@@##        ####@@@@@@@@ ####         ####",
            "@@@@#####     ####@@@@@@@@@#######     #####",
            "@@@@          ####@@@@@@@@@@@         ######",
            "##@@@@    ########@@@@@@@@@@@@@@     #######",
            "##################@@@@@@@@@#################",
            "############################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        },
        background: "dungeon"
    },
    G: {
        bitmap: [
            "#################",
            "##@@@@@@@@@@@@@##",
            "#@@@@@     @@@@@#",
            "#@@@@       @@@@#",
            "####         ####",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "####         ####",
            "#@      1    S @#",
            "#@@@  #####  @@@#",
            "#@@@@@#####@@@@@#",
            "#@@@@#######@@@@#",
            "#@@@@#######@@@@#",
            "#################",
        ],
        entities: {
            '1': (x, y) => new MPowerPillar(x - 0.5, y - 1.8, "ball"),
            'S': (x, y) => new MNPC(x + 0.3, y + 3.5, [
                "You've gained a spike ball.",
                "Click and drag to throw it.",
                "Strategically set up your throws...",
                "...to hit enemies as much as possible.",
                "Press e to resummon the ball without throwing.",
                "Good luck!",
            ], "sign")
        },
        background: "dungeon"
    },
    H: {
        bitmap: [
            "##########@@@@###",
            "##########@@@@@##",
            "###########@@@@@#",
            "###########@@@@@#",
            "##       @##@@@@#",
            "         @##@@@@#",
            "        @@@##@@@#",
            "      @@@@@##@@@#",
            "     @@@@@@@@@@##",
            "     @@@@@@@@@@##",
            "## @@@###########",
            "##@@#############",
            
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        },
        background: "dungeon"
    },
    I: {
        bitmap: [
            "################",
            "################",
            "################",
            "################",
            "#####         ##",
            "##            ##",
            "#            @##",
            "#            @##",
            "#         @  @##",
            "#         @  @##",
            "#         @@ @##",
            "          @@@@##",
            "         @@@@@##",
            "        @@@@@@##",
            "    C @@@@@@@@##",
            "##########@@@@##",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3), 
            'Y': (x, y) => new MMimic(x, y - 0.3),
            'F': (x, y) => new MFlyer(x, y),
            'Q': (x, y) => new MSwarmer(x, y, 5),
        },
        background: "dungeon"
    },
    J: {
        bitmap: [
            "########################",
            "########################",
            "########################",
            "########################",
            "##        @@@@@@@@@@@###",
            "#              @@@@M@@##",
            "#                @@@@@##",
            "#                 ######",
            "                     ###",
            "        @@@@          ##",
            "     @@@@@####        ##",
            "   @@@@ @@##@@          ",
            "# @@@@@@@###@@@@###     ",
            "##@@@M@@@###@@@@@       ",
            "##@@@@@@######@@@       ",
            "########################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        },
        background: "dungeon"
    },
    K: {
        bitmap: [
            "####################################################",
            "######          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##",
            "@@@                    @@@@@@@@@@@       @@@@@@@@@@#",
            "@@@                    @@@@@@@@@            @@@@@@@#",
            "@@@@                    @@@@@@@@              @@@@@#",
            "########    ##            @@@@@               @@@@@#",
            "######      ######                             @@@@#",
            "###### @@@@   ####                                 #",
            "######@@@@@@@ #####                                 ",
            "######@@@@@ @@#####                                 ",
            "######@@@@@@@@######    ####                        ",
            "######@ @@@@@#######                                ",
            "######@@@@@@@@@                ####             ####",
            "######@@@@@@@@@@@      @@@@@@@#####             ####",
            "######@@M@@@@@@@@@@@@@@@@M@@@@######    M      #####",
            "######@@@@@###########@@@@@@@#######           #####",
            "####################################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
            'R': (x, y) => new MBlob(x, y, "r2"),
        },
        background: "dungeon"
    },
    L: {
        bitmap: [
            "######################################",
            "#@         @@@@@@@@@@@@@@@@         @#",
            "@@            @@@@@@@@@@            @@",
            "@@@             @@@@@@             @@@",
            "@@[              @@@@            # ]@@",
            "#####  M                      M  #####",
            "##@@##    ##              ##    ##@@##",
            "#@@@########              ########@@@#",
            "#@@@@######    ##    ##    ######@@@@#",
            "#@@@@@@@@     ##########     @@@@@@@@#",
            "#@@@@@@@@@@@@@##########@@@@@@@@@@@@@#",
            "#@@@@@@@@@@@@############@@@@@@@@@ @@#",
            "#@@@@@@@@@@@@############@@@@@@@@@@@@#",
            "#@@@@@@M@@@@##############@@@@M@@@@@@#",
            "##@@@@@@@@@################@@@@@@@@@##",
            "######################################",
            "######################################",
            "######################################",
            "######################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
            'N': (x, y) => new MNPC(x + 0.2, y - 0.5, [
                "Normally,",
                "This room would be a gauntlet.",
                "The doors at either side would close.",
                "And you'd have to beat up the badguys.",
                "But nobody implemented that yet...",
                "...so you get me, instead.",
                "*Hef, hef, horf!*",
            ], "pakala"),
            "[": (x, y) => new MGauntletDoor(x, y - 2.5, "left"),
            "]": (x, y) => new MGauntletDoor(x, y - 2.5, "right"),
        },
        background: "dungeon"
    },
    M: {
        bitmap: [
            "################",
            "#####@@@@@@@@###",
            "####@@    @@####",
            "###        @@@##",
            "#    @@        #",
            "#@            ##",
            "#@    H  @      ",
            "#@@@            ",
            "###@@@      ####",
            "################",
            "################",
        ],
        entities: {
            'H': (x, y) => new MHatPoint(x, y),
        },
        background: "dungeon"
    },
    N: {
        bitmap: [
            "##@@####################################",
            "#@@@@@                 #################",
            "#@@@@@@@@              #################",
            "###############         ################",
            "################           @@@@@@@######",
            "################               @@@@#####",
            "       @@@@@#######               @@@###",
            "           @@@##            @@@@   @@###",
            "###          @@#     ###  @@@@ @@@  @###",
            "#              #          @@@@@@@@@ @###",
            "#@   ##   @@   #         @###@ @@@@@@###",
            "#@             #         @@@@ @@@@@  ###",
            "#@    @ ##  @@ #          @@@@@###@@@###",
            "#@@            #        @@@@@@@@@@ @@###",
            "#@@@@        ###         @@@@@@@@@@ ####",
            "#@ @@       ####   M    @@@ @@@@@@######",
            "#@@@@    #######         @@@  @@@##@W   ",
            "##@ @@@@              @@@@@@@@@@@@@@    ",
            "######@@@@@     @@@@@@@@@@@@###@@@@     ",
            "########################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
            'W': (x, y) => new MBreakWall(x, y, "brickBreakWall", "right")
        },
        background: "dungeon"
    },
    O: {
        bitmap: [
            "BBBBBBBBBBBBBB####################",
            "BBBBBBBBBBBBB#####################",
            "BBBBBBB###########################",
            "bbbbbbb            ###############",
            "bbbbbb             #####   #######",
            "bbbbbb  b            ### H #######",
            "bbbbbbbbb            ###   #######",
            "bbbbbbbb               #   #######",
            "bbbbbbbb   bbbb        #   #######",
            "BBbbbbbbbbbb               #######",
            "BBbbbbbbbbb                #######",
            "BBBBbbbbbb                 #######",
            "##BBbbbbbb  b              #######",
            "###BBBbbbbbbb              #######",
            "####BBbbbbbb               #######",
            "######BBBbbbb              #######",
            "########BBBbbb C           #######",
            "######################     #######",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'H': (x, y) => new MHatPoint(x, y),
        },
        background: "underground"
    },
    P: {
        bitmap: [
            "BBbbbbbbBBBBBBBBBBBBBB",
            "B   bbbbbbbbbbbBBBBBBB",
            "B   BBBbbbbbbbbbBBBBBB",
            "B         bbbbbbbbbbbb",
            "BB       bb   bbbbbbbb",
            "BB             bbbbbbb",
            "BBBB           bbbbbbb",
            "BBbb  BBBB    bbbbbbbb",
            "Bbb   BBB   BBBB bbbbb",
            "BBbb        BBB    BBB",
            "BBbbbbb            BBB",
            "BBbbbbbbb b       BBBB",
            "BBbbbbbbbbb       BBB#",
            "BBbbbbbbbb     E BBB##",
            "BBbbbbbbbbbbb    BB###",
            "#BBbbbbbbbbb  ########",
            "#####bbbb#############",
            "######################",
            "######################",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
        },
        background: "underground"
    },
    Q: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
            "BBBBBBBBBBB BBBBBBBBBBbbbbBBBBBBBBB",
            "BBBBBBBBB    BBBBBBBBBbbbbbbBBBBBBB",
            "BBBbbbb             bbbbbbbbbbbbbbb",
            "BBbbb bbb              bbbbbbbbbbbb",
            "BBbbb                  bBBBBBBBBBBB",
            "BBbbb                  BBBBBBBBBBBB",
            "BBbb                  BBBbBBBbbBBBB",
            "Bbbbbb               EBBbbBbBbbbBBB",
            "Bbbbb       BB    BBbbbbbbbbBbbbbbb",
            "bbbbbbb    BBBBBBBBBBbbbbbbbbbbbbbb",
            "bbbbbbbbbb BBBBBBBBBBBbbbbbbbbbbBBB",
            "bbbbbbbbbbBBBBBBBBBBBBBbbbbbbbbBBBB",
            "BbbbbbbbbbBBBBBBBBBBBBBbbbbbbbbBBBB",
            "BBbbbbbbBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
        },
        background: "forest"
    },
    R: {
        bitmap: [
            "BBBBBBBBBBBBBBBBB",
            "bbbbbBBBBBBBBBBBB",
            "bbbbbbBBBBBBBBBBB",
            "bbbbbbbbbbbbbBBBB",
            "bbbbbbbbbbbbbbBBB",
            "bbbbbbbbbbbbbbBBB",
            "bbbbbbbbbbbbbbBBB",
            "BBBbbbbbbbbbbbBBB",
            "BBbbbbbbbbbbbBBBB",
            "BBbbbBBBBBBBBBBBB",
            "BBbbbb     bbbBBB",
            "BBBbbbb     bbBBB",
            "BBBbb b     bbbBB",
            "BBBBB        bbbb",
            "BBBBBBB    bbbbbb",
            "BBBbbb  bbbbbbbbb",
            "BBBbbbbbBBBBbbbBB",
            "BBBBBBBBBBBBBBBBB",

        ],
        entities: {

        },
        background: "forest"
    },
    S: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBB      ",
            "BBBBBBBBBB     BBBBBB        ",
            "BBBBBBBBBBB     BB           ",
            "BBBBbbbbbb       BB          ",
            "BBBBBbb                      ",
            "BBbbbbbbb                    ",
            "bbbbbb  bbb                  ",
            "bbbbbb                       ",
            "Bbbbbbbbbb       BBBBBB      ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBB   BBBBBBBBBBBBBBBBBBB",
            "bbbBBb     BBBBBBBBBBBBBBBBBB",
            "bbbbb   H  BBBBBBBBBBBBBBBBBB",
            "BBbbbbb    BBBBBBBBBBBBBBBBBB",
            "BBBBBb    BBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'H': (x, y) => new MHatPoint(x, y),
        },
        background: "forest"
    },
    T: {
        bitmap: [
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "BBBBBB                                      ",
            "BBBBBBBBBBB                                 ",
            "BBBBBBBBBBBBBBB          BBBBBBBBB          ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB      ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {

        },
        background: "forest"
    },
    U: {
        bitmap: [
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                        BBBBB       ",
            "                      BBBBBbbbb     ",
            "            S       BBBBBBBbbbbBB   ",
            "         BBBBBBBBBBBBBBBBBBBbbbBBB  ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",

        ],
        entities: {
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "Awen Outpost\n->",
                "West Castle Tower\n<-",
            ], 'sign'),
        },
        background: "forest"
    },
    V: {
        bitmap: [
            "                                      ",
            "                                      ",
            "                                      ",
            "                                      ",
            "                             $k BB    ",
            "                     p    HHH  BBBBB  ",
            "                  C   BBBBBBBBBBBBBBBB",
            "                  BBbbBBBbbbbBBBBBBBBB",
            "         BBBBBbbbBBbbbbbbbbbbbbbBBBBBB",
            "     BBBBBBBbbbbbBBbbbbbbbbbbbbbbbbBBB",
            "    BBBBBBBbbbbbBBbbbbbbbbbbbbbbbbbbBB",
            "   BBBBBBBBbbbbBBBbbbbbbbbbbbbbbbbbbBB",
            " BBBBBBBBBBbbbBBbbbbbbbbbbbbbbbbbbbbBB",
            "BBBBBBBBBBBbbbbbbbbbbbbbbBBBBBBBBbbbBB",
            "BBBBBBBBBBBBbbbbbbbbbbbbbbBBBBbbBbbbBB",
            "BBBBBBBBBBBBbbbbbbbbbbbbbbbBBbbbBbbbBB",
            "BBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbBbbbBB",
            "BBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbbbbbBB",
            "BBBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbbbbBB",
            "BBBBBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'p': (x, y) => new MNPC(x + 0.5, y + 13.5, [
                "Pona, Pona, jan lili pi mi!",
                "Welcome back to Awen!",
                "I see you've found a way to defend yourself!",
                "Could you perhaps grant us your protection as well?",
            ], 'pakala'),
            'k': (x, y) => new MNPC(x, y + 7, [
                "Pona, Pona!",
                "I'm surprised you could reach me up here!",
                "It's quite a feat to climb so high.",
                "You can have these coins.",
                "As a reward for yourself.",
                "I wish you luck on your journey!",
            ], "kasi"),
            '$': (x, y) => new MHatShop(x, y + 14),
            'C': (x, y) => new MCheckpoint(x, y + 10),
            'H': (x, y) => new MHatPoint(x, y + 6)
        }, // Lotsa NPCs for this one. :)
        background: "forest"
    },
    W: {
        bitmap: [
            "                              ############@@@@@@############",
            "                              ###########@@@@@@@@###########",
            "                            ############@@@@##@@@@##########",
            "                            ###########@@@@####@@@@#########",
            "                          ############@@@@######@@@@########",
            "  S      BB      E     BBB###########@@@@########@@@@#######",
            "BBBBBBBBBBB          BBB############@@@@##########@@@@######",
            "BBBBBBBBBBBBBBBBBBBBBBBB###########@@@@############@@@@#####",
            "BBBBBBBBBBBBBBBBBBBBBB############@@@@##@@@@@@@@@@##@@@@####",
            "BBBBBBBBBBBBBBBBBBBBBB###########@@@@##@@@@@@@@@@@@##@@@@###",
            "BBBBBBBBBBBBBBBBBBBB############@@@@##@@@@@@@@@@@@@@##@@@@##",
            "BBBBBBBBBBBBBBBBBBBB############@@@##@@@@###@@###@@@@##@@@##",
            "BBBBBBBBBBBBBBBBBBBB###########@@@##@@@@@@##@@##@@@@@@##@@@#",
            "BBBBBBBBBBBBBBBBBB#############@@##@@@@@@@##@@##@@@@@@@##@@#",
            "BBBBBBBBBBBBBBBBBB#############@@@@@@@@@@@##@@##@@@@@@@@@@@#",
            "BBBBBBBBBBBBBBBB################@@@@@@@@@@##@@##@@@@@@@@@@##",
            "BBBBBBBBBBBBBBBB############################@@##############",
            "BBBBBBBBBBBBBBBB############################@@##############",
            "BBBBBBBBBBBBBBBB############################@@##############",
            "BBBBBBBBBBBBBBBB####################@@@@@###@@##############",
            "BBBBBBBBBBBBBB#####################@@@@@@@##@@##############",
            "BBBBBBBBBBBBBB#####################@@@@@@@@@@@##############",
            "BBBBBBBBBBBBBB#####################@@@@@@@@@@@##############",
            "BBBBBBBBBBBBBB#######################@@@####################",
        ],
        entities: {
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "Awen Outpost\n<-",
                "Central Castle Tower\n->",
            ], 'sign'),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
        },
        background: "forest"
    },
    X: {
        bitmap: [
            "                                          H    H            ",
            "                                    ##  ##  ##  ##  ##      ",
            "   ##                               ##  ## C##  ##  ##      ",
            "  ###                               ##################      ",
            "  ##                                ##################      ",
            "  ##  H                             ##@@@@@@@@@@@@@@##      ",
            "  ##     ##                         ##@@@@@@@@@@@@@@##      ",
            "  ##    ###                         ##@@@@@@@@@@@@@@##      ",
            "  ##    ##                          ##@@@@@@@@@@@@@@##      ",
            "  ##    ##                          ##@@@@@@@@@@@@@@##      ",
            "  ########                          ##@@@@@@@@@@@@@@##      ",
            "   ######                           @@@@@@@@@@@@@@@@@@      ",
            "                                    @@@@@@@@@@@@@@@@@@      ",
            "                                    @@@@@@@@@@@@@@@@@@      ",
            "                                  ####@@@########@@@####BB  ",
            "                                  #####@@@######@@@#####BBBB",
            "                                ########@@@@@@@@@@########BB",
            "                                #########@@@@@@@@#########BB",
            "                              ############@@@@@@############",
        ],
        entities: {
            "C": (x, y) => new MCheckpoint(x + 1, y + 8),
            'H': (x, y) => new MHatPoint(x, y),
        },
        background: "forest"
    },
    Y: {
        bitmap: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "            H  eE           ",
            "       bbBBBBBBbbb          ",
            "    BBbbbbbbbbbbbbBBB       ",
            "   BBBbbbbbbbbbbbbbBBBBBBBBB",
            "BBBBBBBbbbbbbbbbbbbBBBBBBBBB",
            "BBBBBBBBBbbbbbbbbbBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'H': (x, y) => new MHatPoint(x, y + 4),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "WARNING",
                "Chasm ahead.",
                "To avoid falling, excercise caution.",
                "Central Castle Tower <-",
            ], "sign"),
        },
        background: "forest"
    },
    Z: {
        bitmap: [
            "###@@@#######BBBBB",
            "###@@@@####bbbbbbb",
            "####@@@###bbbbbbbb",
            "##@@@@@### bbbbbbb",
            "##     ##B  bbbbbb",
            "##     #BB    bbbb",
            "##b    #BB     bbb",
            "##bbb  BBBBO  BBBB",
            "##bbb  B      BBBB",
            "##bbbb       BB  B",
            "###bbbbbbb ###B  B",
            "#######bbbbb###  B",
            "#########bbb@@@@ B",
            "#########bb@@@@@BB",
            "##########b@@@@@BB",
            "###########@@@###B",
        ],
        entities: {
            "S": (x, y) => new MNPC(x - 0.3, y - 2.5, [
                "There should be...",
                "A ground pound floor here."
            ], "sign"),
            "O": (x, y) => new MPoundFloor(x, y, "grassy"),
        },
        background: "underground",
    },
    a: {
        bitmap: [
            "",
            "                              H",
            "",
            "                                   ",
            "                            BBBBB  ",
            "                            BBBBB  ",
            "                             BBB   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "          bbbbb                    ",
            "      BBBbbbbbbbBBbbb  BB          ",
            "      BBBBbbbbbbBBBBbbbbb     S    ",
            "  P  BBBBBbbbbBBBBBBbbbbbbbBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBbbbbBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBbbbbbbbBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBbbbbbbbBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBbbbbBBBBBBB",
        ],
        entities: {
            'J': (x, y) => new MEnvironment(x, y, 'bush1'),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "Central Castle Tower\n<-",
                "Shroom Field\n->"
            ], "sign"),
            'H': (x, y) => new MHatPoint(x, y),
            
        },
        background: "forest"
    },
    b: {
        bitmap: [
            "                bbbbbbbbBBBB",
            "                  bbbbbbBBBB",
            "                   EbbbBBBBB",
            "   bbb         BBbbbbbBBBBBB",
            " BBBBbbbbb   BBBBBBBBBBBBBBB",
            " BBBbbbbbbbb   bbbbbBBBBBBBB",
            "  bbbbbBBBBbbbbbbbbbbBBBBBBB",
            "     bbbBBBbbbbbbbbbbBBBBBBB",
            "       bbbbbbBBBBbbbbBBBBBBB",
            "        bbbbbBBBbbbBBBBBBBBB",
            "        EbbbbbbbbbbBBBBBBBBB",
            "        bbbbbbbbbbBBBBBBBBBB",
            "   BBBBbbbbbbbbbBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            e: (x, y) => new MBlob(x, y, "g1"),
        },
        background: "forest"
    },
    c: {
        bitmap: [
            "",
            "",
            "",
            "                               ",
            "                     BBBBB     ",
            "                  BBBBBBBBBBB  ",
            "                 BBBBBBBBBBBBBB",
            "               BBBbbbbbBBBBBBBB",
            "              bBBbbbbbbbBBBBBBB",
            "          BBBbbbbbbbbbbbBBBBBBB",
            "          BBbbbbbbbbbbbbbBBBBBB",
            "             bBBBbbbbbbbbBBBBBB",
            "              BBbbbbbbbbbBBBBBB",
            "               bbbbBBBbbbBBBBBB",
            "               bbbbBBbbbbBBBBBB",
            "               bbbbbbbbbBBBBBBB",
        ],
        entities: {

        },
        background: "forest"
    },
    d: {
        bitmap: [
            "                   ^",
            "                   ^",
            "                   ^",
            "                    ",
            "                    ",
            "                    ",
            "BB                  ",
            "BBB                 ",
            "BBB                 ",
            "BBBB                ",
            "BBBB            ^^^ ",
            "BBBBBB           ^^ ",
            "BBBBBB     ^^^      ",
            "BBBBBBB     ^^      ",
            "BBBBBBB             ",
            "BBBBBBBB            ",
        ],
        entities: {

        },
        background: "forest"
    },
    e: {
        bitmap: [
            "BBBBBBBB                ",
            "BBBBBBBB                ",
            "BBBBBBBB                ",
            "BBBBBBBB                ",
            "BBBBBBBBB               ",
            "BBBBBBBBB               ",
            "BBBBBBBBB               ",
            "BBBBBBBBB             bb",
            "BBBBBBBBB            bbb",
            "BBBBBBBBB            bbb",
            "BBBBBBBBB          M bbb",
            "BBBBBBBBBB          bbbb",
            "BBBBBBBBBB^^^      bbbbb",
            "BBBBBBBBBB^^^^^^^^^^^^^^",
            "BBBBBBBBBB^^^^^^^^^^^^^^",
            "BBBBBBBBBBB^^^^^^^^^^^^^",
        ],
        entities: {
            'M': (x, y) => new MFlyer(x, y),
        },
        background: "forest"
    },
    f: {
        bitmap: [
            "                                ",
            "                                ",
            "                                ",
            "                                ",
            "               C                ",
            "             bbbbbb             ",
            "            bbbbbbbb            ",
            "bbb   M     bbbbbbbb    M    bbb",
            "bbbb        bbbbbbbb        bbbb",
            "bbbb        bb^^^^bb        bbbb",
            "bbbbb      bbbbbbbbbb      bbbbb",
            "bbbbbbbbb^^^^bbbbbb^^^^bbbbbbbbb",
            "bbbbbbbb^^^^^^^^^^^^^^^^bbbbbbbb",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^^^^^^^^^##^^^^^^^^##^^^^^^^^^^",
            "^^^^^^^^################^^^^^^^^",
        ],
        entities: {
            'M': (x, y) => new MFlyer(x, y),
        },
        background: "forest"
    },
    g: {
        bitmap: [
            "^                      ^  ^",
            "^                      ^  ^",
            "^                      ^ ^^",
            "                    ^  ^  ^",
            "                    ^^ ^  ^",
            "                     ^^^^ ^",
            "       ^^              ^  ^",
            "       ^^       H      ^  ^",
            " ^^^   ^^              ^  ^",
            "  ^^   ^^^^^^^     ^^^^^  ^",
            "        ^^^^^^^   ^^^^^  ^^",
            "             ^^   ^^      ^",
            "             ^^   ^^      ^",
            "              ^   ^       ^",
            "                           ",
            "",
            "",
        ],
        entities: {
            "H": (x, y) => new MHatPoint(x, y),
        },
        background: "forest"
    },
    h: {
        bitmap: [
            "   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   ^^^^",
            "   ^^^^^bbbbbbbbbbbbbbbbbbbbbbbb     ^^^^",
            "   ^^^^bbbbbbbbbbbbbbbbbbbbbbbb    ^^^^^^",
            "   ^^^^bbW^^^^^^^^^^^^^^^^^^^^b    ^^^^^^",
            "   ^^^^bbbbbbb^^^^^^^^^^^^^^^^b   ^^^^^^^",
            "   ^^^^^bbbbbb^^bbbbbbbbbbbb^^^   ^^^^^^^",
            "   ^^^^^^^^^bb^bbbbbbbbbbbbbb^^^   ^^^^^^",
            "   ^^^        ^bbbbbbbbbbbbbb^^^   ^^^^^^",
            "   ^^^       ^^bbbbbbbbbbbbbbb^^^    ^^^^",
            "   ^^^  ^^^^^^^bbb^^^^bbbb    ^^^    ^^^^",
            "   ^^^  ^ e    bbb^^^bbbbb     ^^^   ^^^^",
            "             bbb^^^^                 ^^^^",
            "            ^^^^^^^^                ^^^^#",
            "^^^^^^^^^^^^^^^^^^^^     C       ^^^^^^##",
            "^^^^^^^^^########^^^^^^^^^^^^^^^^^^^^####",
            "^^^^^^############^^^^^^^^^^^^^^^^^^#####",
        ],
        entities: {
            'M': (x, y) => new MFlyer(x, y),
            "C": (x, y) => new MCheckpoint(x, y - 3),
            "W": (x, y) => new MBreakWall(x, y, "mushroomBreakWall", "right"),
        },
        background: "forest"
    },
    i: {
        bitmap: [
            "^^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^^bbb^^^            bbbbbbbbbbbb^^^^^^^^^",
            "^^^bbb^^               Hbbbbbbbbb^^^^^^^^^",
            "^^^bbb^^                 bbbbbbbb^^^^^^^^^",
            "^^^bbb^^                 bbbb^^^^^^^^^^^^^",
            "^^^bbb^^                 bbbb^^^^^^^^^^^^^",
            "^^^bbb^^b S     1         bbb^^^^^^bbbbb^^",
            "^^^bbb^bbbb ^^^^^^^^         ^^^^^bbbbbbb^",
            "^^^bbb^bbbb^^^^^^^^^^        ^^^^^bbbbbbb^",
            "^^^bbbbbbbb^^^^^^^^^^        ^^^^^bbbbbbb^",
            "^^^bbbbbbb^^^^^^^^^^^^       ^^^^   bbbbb^",
            "^^^bbbbbbb^^^^^^^^^^^^               bbbb^",
            "^^^^bbbbb^^^^^^^^^^^^^^               bb^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^         ^^^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   ^^^^^",
        ],
        entities: {
            '1': (x, y) => new MPowerPillar(x - 1, y - 1.8, "wallJump"),
            "H": (x, y) => new MHatPoint(x + 8, y),
            'S': (x, y) => new MNPC(x - 5, y + 5.5, [
                "Congratulations on unlocking walljump.",
                "Repeatedly jump near a wall to climb up.",
                "Timing your jumps correctly allows for faster climbing..",
                "...So be careful about it.",
                "Good luck!",
            ], "sign"),
        },
        background: "forest"
    },
    j: {
        bitmap: [
            "^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^bbbbbbbbbbbbb         bbbbb^^^^^^^^^^^^^",
            "^^bbbbbbbbbbbbb    F     bbbb^^^^^^^^^^^^^",
            "^^bbbbbbbbbbbb^^^        bbbbbbb^^bbbb  ^^",
            "^^bbbbbbbbbbb^^^^          bbbbb^^bb    ^^",
            "^^^bbbbbbbbbb^^^^    ^^^^^^^^^^b^^b^^   ^^",
            "^^^^^^^^^^^^^^^^^     ^^^^^^^^^bbbb^^   ^^",
            "^^^^^^^^^^^^^^^^             ^^bbbb^^   ^^",
            "^^^^^^^^^^^^^^               ^^    ^^   ^^",
            "^^^^^^^^^^^^^         F      ^^    ^^   ^^",
            "^^^bbbb^^^^^^                           ^^",
            "^^bbbbbb^^^^^                           ^^",
            "^^bbbbbbb^^^                            ^^",
            "^^bbbbbbbbb     ^^^O  ^^^              ^^^",
            "^^bbbbbbbbb  ^^^^^^^H^^^^^^^^^^^^^^^^^^^^^",
            "^^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        ],
        entities: {
            'S': (x, y) => new MSwarmer(x, y),
            'F': (x, y) => new MFlyer(x, y),
            'O': (x, y) => new MPoundFloor(x, y, "mushroom"),
            'H': (x, y) => new MHatPoint(x + 0.1, y + 0.15),
        },
        background: "forest"
    },
    k: {
        bitmap: [
            "^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^bbbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^^bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^^",
            "^^bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^",
            "^^bbbb[bbbbbbbbbbbbbbb^^^bbbbbbbbbbbbbb^^^",
            "^^^^^^^^bbbbbbbbbbbbbb^^^bbbbbbbbbbbbbb^^^",
            "^^^^^^^^^bbb^^^^^bbbbb^^^bbbb^^^^^^bbbb^^^",
            "^^^^^^^^^bbb^   bbbbbb^^^bbbbbb   ^bbbb^^^",
            "^^^^^^^^^bbb^ S bbbbbb^^^bbbbbb S ^bbbb^^^",
            "^^^^^^^^^bbb^   bbbbbb^^^bbbbbb   ^bbbb^^^",
            "^^^^^^^^bbbb^^^^^bbbbb^^^bbbb^^^^^^bbbb^^^",
            "^^bbbbbbbbbbbbbbbbbbbb^^^bbbbbbbbbbbbbb^^^",
            "^bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^",
            "^bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^",
            "^bbbbb[bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb^^^^",
            "^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        ],
        entities: {
            'S': (x, y) => new MSwarmer(x, y),
            'F': (x, y) => new MFlyer(x, y),
            "[": (x, y) => new MGauntletDoor(x, y - 2.5, "left"),
            "]": (x, y) => new MGauntletDoor(x, y - 2.5, "right"),
        },
        background: "forest"
    },
    l: {
        bitmap: [
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "^bb^^^^^bbbb^^bb^^^bbb^bbbbbb          ^^^",
            "bbbb^bbbbbbbb^bbbbbbbbbbbbbbbb          ^^",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb          ^^",
            "^^^bbb^^^^^^bbbb^^^^^bbb^^bbbb   ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^b    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^    ^^",
            "^^^^^^^^^^^^^^^^^^^^^^^^^^^^     ^^^    ^^",
            "^^bbbbb                          ^^^    ^^",
            "^bbbbbbb                                ^^",
            "^bbbbbbb                                ^^",
            "^bbbbbbb                               ^^^",
            "^^bbb^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        ],
        background: "forest"
    },
    m: {
        bitmap: [
            "             ^^^^^^^^^^^^^^",
            "                  ^^^^^^^^^",
            "                    ^^^bbbb",
            "                    ^^^bbbb",
            "^^^^^^               ^^bb^^",
            "^^                   ^^bbb^",
            "^                    ^^bbb^",
            "^                    ^^^bb^",
            "^                    ^^^bb^",
            "^                    ^^^bb^",
            "^^^                  ^^^bb^",
        ],
        background: "forest"
    },
    n: {
        bitmap: [
            "^^^                  ^^^bb^",
            "^^^                  ^^^bb^",
            "^^                   ^bbbb^",
            "^           HHH      ^bbb^^",
            "^          ^^^^^     ^bbbb^",
            "^    ^^^    ^^^      ^^^bb^",
            "^     ^^               ^^b^",
            "^     ^^               ^bb^",
            "^          ^^^         ^bb^",
            "^         ^^^^         ^bb^",
            "^         ^^^   ^^^    ^bb^",
            "^         ^^^    ^^    ^bb^",
            "^         ^^^          ^bb^",
        ],
        entities: {
            "H": (x, y) => new MHatPoint(x + 0.1, y),
        },
        background: "forest",
    },
    o: {
        bitmap: [
            "^         ^^^          ^bb^",
            "^         ^bb          ^bb^",
            "^         ^bbb         ^b^^",
            "^         ^bb^^    ^^^^^bb^",
            "^         ^bb^        ^^bb^",
            "^         ^^^^         ^^b^",
            "^          ^^^         ^bb^",
            "^                      ^bb^",
            "^                ^^^   ^bb^",
            "^                 ^^   ^bb^",
            "^                      ^bb^",
        ],
        background: "forest",
    },
    p: {
        bitmap: [
            "",
            "",
            "",
            "                                   ",
            "        bbbbbC         #           ",
            "      bbbbbbbb       @##           ",
            "BBB  bbbbb#b#b# # @@@@##           ",
            "BBBBBBBbbb#######@@@@@##           ",
            "BBBBBBBbbb##@@@##@@@@@#         BBB",
            "BBBBBBBbbb#@@@@@#@@@@bb        BBBB",
            "###BBBBbbb#@@@@@#@@@bbbb       BBBB",
            "###BBBBbb@@@@@@@@@@@bbbb       BBBB",
            "###BBBB@@@@@@@@@@@@@bbbbb      BBBB",
            "####BBBBBB#######BBBbbbbbbbb  BBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBbbbBBBBBBBBBB",
        ],
        entities: {
            "N": (x, y) => new MPothead(x, y),
            'C': (x, y) => new MCheckpoint(x - 0.75, y + 5),
        },
        background: "forest"
    },
    q: {
        bitmap: [
            "",
            "",
            "",
            "                                   ",
            "BBBbbb                             ",
            "BBBBbb                             ",
            "BBBBbbb                       BBBBB",
            "BBBBbbbbbb  N     bbbbbbb N  BBBBBB",
            "BBBBbbbbbbbbb   bbbbbbbbbbb@@###BBB",
            "BBBBbbbbb@@@@@@B@@bbbbbbbb@@@###BBB",
            "BBBBBbbbbbb@@@bBBbbbbbbbb@@@@######",
            "BBBBBBBBB@@@@@BBBBbbbbbbb@@@@######",
            "BBBBBBB####BBBBBBBBbbbbbbb@@@######",
            "BBBBBB####BBBBBBBBBBBBBBBBBB#######",
            "BBBBBB##########BBBBBBBBB##########",
            "BBBB######BBBBBBBBBBBBBBBBB########",
        ],
        entities: {
            "N": (x, y) => new MPothead(x, y),
        },
        background: "forest"
    },
    r: {
        bitmap : [
            "#####         ",
            "###@@         ",
            "##@@@@        ",
            "##@@@@@@@     ",
            "##@@@@@###BBBB",
            "##@@@@####BBBB",
            "##@@@@##BBBBBB",
            "##@@@@@#BBBBBB",
            "##@@@@@#BBBBBB",
            "##@@@@@#BBBBBB",
            "####@@@##BBBBB",
            "##@@@@@###BBBB",
            "##@@@@@###BBBB",
            "##@@@@@###BBBB",
            "###@@@#####BBB",
        ],
        background: "forest"
    },
    s: {
        bitmap: [
            "##############",
            "##############",
            "##############",
            "##############",
            "######     ###",
            "#####       ##",
            "#####       ##",
            "#####     H ##",
            "#####       ##",
            "#####   ######",
            "#####    #####",
            "#####         ",
            "#####         ",
        ],
        entities: {
            'H': (x, y) => new MHatPoint(x, y)
        },
        background: "forest"
    },
    t: {
        bitmap: [
            "###########@@@########",
            "########@@@@@@########",
            "#######@@@@@@@########",
            "######@@@@@@@#########",
            "######@@@@@@@#########",
            "######@@@@@@##########",
            "######@@@#############",
            "######@@@@@@@@@@@@@###",
            "#######@@@    @@@@@@##",
            "#######@@      @@@@@##",
            "########@       @@@@@#",
            "########@       @@@@@#",
            "########## C    @@@@@#",
            "#################@@@@#",
        ],
        entities: {
            "C": (x, y) => new MCheckpoint(x, y - 3),
        },
        background: "dungeon"
    },
    u: {
        bitmap: [
            "#################@@@@####################",
            "###########@@@@@@@@@@@@@@@@##############",
            "##########@@@@@@@@@@@@@@@@@@#############",
            "#########@@@@@@        @@@@@@############",
            "#########@@@@@   #  #   @@@@@@@@@@@@@@###",
            "#########@@@@@   ####   @@@@@@@@@@@@@@@##",
            "#########@@@@   ##@@##   @@@@@@@@@@@@@@##",
            "#########@@@@ Y #@@@@# ] @@@@@@@@@@@@@@##",
            "#########@@@@  ##@@@@##  @@@@@@#####@@@##",
            "#########@@@@  ##@@@@##  @@@@@####@@@@@##",
            "#########@@@@ ####@@#### @@@@@####@@@@###",
            "##########@@@ #@@####@##@@@@@#####@@@@@@#",
            "##########@@@###@@@@@@###@@@@#######@@@@#",
            "##################################@@@@@@#",
            "##################################@@@@@##",
            "##################################@@@@@##",
            "###################################@@@###",
        ],
        entities: {
            "[": (x, y) => new MGauntletDoor(x - 4, y - 2.5, "left"),
            "]": (x, y) => new MGauntletDoor(x + 9, y - 2.5, "right"),
            "Y": (x, y) => new MMimic(x, y),
        },
        background: "dungeon"
    },
    v: {
        bitmap: [
            "###################################@@@####",
            "################################@@@@@@####",
            "###############################@@@@@@@####",
            "###############################@@@#@@#####",
            "###############################@@@########",
            "##############################@@@@@#     #",
            "############                 @@@@@@#   H #",
            "###########                     @@@#  #  #",
            "###########                      @@#  ####",
            "###########        2            ####     #",
            "###########     #######                  #",
            "###########    #########    ###          #",
            "############ S #########    ###          #",
            "##########################################",
            "##########################################",
        ],
        entities: {
            '2': (x, y) => new MPowerPillar(x, y - 1.8, 'groundedTeleport'),
            'S': (x, y) => new MNPC(x - 0.3, y - 0.5, [
                "You've recieved an upgrade to your spike ball!",
                "Now, you can click to teleport to it!",
                "...But only while the ball is on the ground",
                "So you'll need to be strategic about it.",
                "Have fun, using it to reach new places!",
            ], "sign"),
            'H': (x, y) => new MHatPoint(x, y),
        },
        background: "dungeon"
    },
    w: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBBBbbbbB",
            "###########BBBBBBBBBBBBbbbbbB",
            "###########BBBBBBBBBBBBbbbbBB",
            "###     ####BBBBBBBBBBbbbbbBB",
            "##       #########BBBBbbbbBBB",
            "##        bbbbb######bbbbbBBB",
            "##   H   bbbbbbbbbbbbbbbbBBBB",
            "##       BBBbbbbbbbbbbbbbBBBB",
            "###     BBBBBBbbbbbbbbbbBBBBB",
            "###########BBBBBbbbbbbbbBBBBB",
            "#########BBBBBBBBBbbbbbBBBBBB",
            "##########BBBBBBB#bbbbb###BBB",
            "##################bbb######BB",
        ],
        entities: {
            "H": (x, y) => new MHatPoint(x, y - 0.5),
        },
        background: "underground"
    },
    x: {
        bitmap: [
            "##################bbb########",
            "#################bbbbb@@@####",
            "#######==########bbbbb@@@@###",
            "######===     #####bb  @@@###",
            "######==       #######  @@###",
            "#####===                @####",
            "##=======              @@####",
            "#===bbb==b    C      @@@#####",
            "#==bbbbbbb         @@@@@#####",
            "#==bbbbbbbb       @@@@@######",
            "#==bbbbbbbbbb     @@@@@######",
            "##==bbb======################",
        ],
        entities: {
            "C": (x, y) => new MCheckpoint(x, y),
        },
        background: "underground"
    },
    y: {
        bitmap: [
            "#===bbb=======####################",
            "##==bbbbbbbbbbbbbbb###############",
            "##==bbbbbbbbbbbbbbbb##=========###",
            "#===========bbbbbbbbbbb===========",
            "==bbbbbbbb========bbbbbbbbbb======",
            "=bbbbbbbbbbb======bbbbbbbbbbbbbb==",
            "=bbbbbbbbbbb=========bbbbbbbbb   =",
            "=bbbbbb==bbbb=====bbbbb===bbb    =",
            "=bbbbbb===bbbb===          bb    =",
            "=bbbb=====bbbb==         bbb==O  =",
            "=bbbbbbb===bbbb   p     bbbb===H==",
            "==bbbbbb===bbbbbb    bbbbb========",
            "==bbbbbb==========================",
            "===bbbb===========================",
        ],
        entities: {
            'H': (x, y) => new MHatPoint(x, y + 0.2),
            'O': (x, y) => new MPoundFloor(x, y, "brick"),
            'p': (x, y) => new MPothead(x, y),
        },
        background: "underground"
    },
    z: {
        bitmap: [
            "===bbbb=============================",
            "===bbbbbbb    ===            bbbbbbb",
            "====bbbbbb                 bbbbbbbbb",
            "======bbbbbbbb  bbbbbbbbb bbbbb==bbb",
            "====bbbb=bbb=bbbbbb=bbb=bbbbbbb=====",
            "===bbbbb=bbb=bb=bbb=bbb=bbbbbbb=====",
            "===bbbbbbbbb=bb=bbb=bbbbb bbbbb=====",
            "====bbbb   bbbb=bbbbb       bbbb====",
            "=====bbb     bbbbb          ==bb====",
            "===LLLLLLLLLLLLLLLLLLLLLLLLL=bbb====",
            "===LLLLLLLLLLLLLLLLLLLLLLLLL=bb=====",
            "===LLLLLLLLLLLLLLLLLLLLLLLLL=bbbbb==",
            "==LLLLLLLLLLLLLLLLLLLLLLLLLL==bbbbb=",
            "==LLLLLLLLLLLLLLLLLLLLLLLLL===bbbbb=",
            "===LLLLLLLLLLLLLLLLLLLLLLLL==bb=LLL=",
            "===LLLLLLLLLLLLLLLLLLLLLLLL==bb==LL=",
            "===LLLLLLLLLLLLLLLLLLLLLLL===b======",
        ],
        entities: {
            "L": (x, y) => new MLava(x, y),
            "W": (x, y) => new MBreakWall(x, y, "brickBreakWall", "right")
        },
        background: "underground"
    },
    1: {
        bitmap: [
            "====LLLLLLLLLLLLLLLLLLLL=====b======",
            "======LLLLLLLLLLLLLLL=======bbbb====",
            "==========LLLLLL============bbbb====",
            "==============================bb====",
            "=============================bbb====",
            "====bbb===========   =======bbb=====",
            "===bbbbbbbb           =====bbb======",
            "==bbbbbbb b b         ===bbbb=======",
            "==bbMbbbbbb bb          bbbbb=======",
            "==bbbbbb=bbbb            bbb========",
            "=========bbbbb           bbb========",
            "======bbbbb==bbb       [  b=========",
            "=====    bb===bbbbbb  ==============",
            "=====     bbbbbbbbbbb  ==     ======",
            "======     bbb b===bb            ===",
            "          bbbbbbbbbbb             ==",
            "       bbbb===bbb bb  ===         ==",
            "       bbbbbbbb bbb             M ==",
            "   ]  ===bb b               ==    ==",
            "=========bbbbb               =======",
            "=======LLLLLLLLLLLLLLLLLLLLLL=======",
            "====LLLLLLLLLLLLLLLLLLLLLLLLL=======",
            "====LLLLLLLLLLLLLLLLLLLLLLLL========",
            "=====LLLLLLLLLLLLLLLLLLLLLLL========",
        ],
        entities: {
            "L": (x, y) => new MLava(x, y),
            "p": (x, y) => new MPothead(x, y),
            "M": (x, y) => new MMinitaur(x, y),
            "[": (x, y) => new MGauntletDoor(x, y - 2.5, "right"),
            "]": (x, y) => new MGauntletDoor(x, y - 2.5, "left"),
        },
        background: "underground"
    },
    2: {
        bitmap: [
            "##################=========",
            "######################=====",
            "##############=============",
            "###################========",
            "##################=========",
            "###################========",
            "#######           ####=====",
            "####               bbb=====",
            "###                 bbb====",
            "###                 bbb====",
            "###                 bbb====",
            "###                  bb====",
            "###                  bb====",
            "###                  bbb===",
            "###    S    1         bbb==",
            "###O  ###########     bbbbb",
            "@@@@@@###########bbbbbbbbbb",
            "@@@@@#############bbbbbbbbb",
            "@@@@@#############bbbbbbbbb",
            "####################=======",
        ],
        entities: {
            'O': (x, y) => new MPoundFloor(x, y, "brick"),
            '1': (x, y) => new MPowerPillar(x, y - 1.8, "groundPound"),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "You've unlocked the groundpound ability.",
                "Press the S key to slam into the ground.",
                "In the process, dealing damage to nearby enemies...",
                "...And breaking any weak floors beneath you!",
                "Go ahead and give it a try!",
            ], "sign")
        },
        background: "underground"
    },
    3: {
        bitmap: [
            "=============================",
            "   ======    =             ==",
            "             =              =",
            "           =   =            =",
            "=====  =   =   =      H H H =",
            "====   =   =   =            =",
            "====LLL=   =   =    =========",
            "====LL==LLL=   =LLLLLLL======",
            "====LL==LLL=LLL=LLLLLLLL=====",
            "====LL==LLL==L==LLLLLL=======",
            "====LL==LL===L==LLLLLL=======",
            "====LL==LL===L==LLLLLL=======",
            "====LL===L=======LLLLL=======",
            "====L====L========LLLL=======",
        ],
        entities: {
            "H": (x, y) => new MHatPoint(x, y),
            "L": (x, y) => new MLava(x, y),
            "1": (x, y) => new MPowerPillar(x, y, "wallJump"),
        },
        background: "underground"
    },
    4: {
        bitmap: [
            "#####################################@@@############",
            "####################@@@@@@@#####@@@@@@@@############",
            "####   #   ########@@@@@@@@##### @@@@@@@############",
            "###################@@@@@@@@ ###  @@@@@@#############",
            "###   ###   #######@@@@@@@@     @@@@@@@#############",
            "### M ### M #######@@@@@@@@@   @@@@@@@##############",
            "###   ###   ########@@@@@@@@   @@@@@@@##############",
            "######################@@@##@ [  @@@@@######   ######",
            "######   #############@@@#################     #####",
            "#####     #########@@@@@@@@@@@                      ",
            "#####     #########@@     @@@                       ",
            "#####     #########@   1   @@                       ",
            "###################  #####  @@   S          C       ",
            "####################################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
            "[": (x, y) => new MGauntletDoor(x, y - 2.5, "right"),
            "C": (x, y) => new MCheckpoint(x - 0.6, y - 3),
            "1": (x, y) => new MPowerPillar(x - 0.3, y - 1.8, "fullTeleport"),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "You've unlocked the ability to teleport literally anywhere.",
                "You don't need the ball to be on the ground anymore.",
                "You can literally just fly forever.",
                "You need this to defeat the one.",
                "His name is Fthwêržħwlbã't, but everyone calls him Fred,",
                "because, let's be real, NO one can pronounce that...",
                "right...?",
                "?????",
            ], "sign")
        },
        background: "dungeon",
    },
    5: {
        bitmap: [
            "###############################################",
            "###############################################",
            "###############################################",
            "##                                         ####",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "                                            ###",
            "                                  X         ###",
            "                                            ###",
            "[                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "#                                           ###",
            "##                                         ####",
            "###############################################",
            "###############################################",
            "###############################################",
        ],
        entities: {
            'X': (x, y) => new MPacman(x, y, "Fthwêržħwlbã't"),
            "[": (x, y) => new MGauntletDoor(x, y - 2.5, "left"),
            "]": (x, y) => new MGauntletDoor(x, y - 2.5, "right"),
        },
        background: "dungeon",
        final: true,
    },
    6: {
        bitmap: [
            "                            ",
            "                            ",
            "                            ",
            "                 BBBB       ",
            "                   BBB      ",
            "                    BBB     ",
            "               H    BBB     ",
            "                   BBBB     ",
            "BBBB               BBBB     ",
            "BBBBBBBBBBBBB     BBBBB     ",
            "BBBBBBBBBBBBBBBBBBBBBBB     ",
            "BBBBBBBBBBBBBBBBBBBBBBB     ",
        ],
        entities: {
            'H': (x, y) => new MHatPoint(x, y),
        },
        background: "forest",
    },

    0: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                          ",
            "B                                          ",
            "B                                          ",
            "B                                   1234   ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            '1': (x, y) => new MPowerPillar(x, y - 1.8, 'ball'),
            '2': (x, y) => new MPowerPillar(x, y - 1.8, 'groundedTeleport'),
            '3': (x, y) => new MPowerPillar(x, y - 1.8, 'groundPound'),
            '4': (x, y) => new MPowerPillar(x, y - 1.8, 'fullTeleport'),
            "N": (x, y) => new MPothead(x, y),
            'X': (x, y) => new MPacman(x, y)
        },
    },
    ℤ: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "B                                         B",
            "B                                         B",
            "B                                X        B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "B                                         B",
            "                                           ",
            "                                           ",
            "                                           ",
            "[                                         ]",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            "N": (x, y) => new MPothead(x, y),
            'X': (x, y) => new MPacman(x, y),
            "[": (x, y) => new MGauntletDoor(x, y - 2.5, "left"),
            "]": (x, y) => new MGauntletDoor(x, y - 2.5, "right"),
        },
    },
    λ: {
        background: 'bushes', 
        bitmap: [
            
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B                                 B",
            "B          BBBB     BBBBBBBBB     B",
            "B         BBBBBBBBBBBBBBBBBBBBBBBBB",
            "B         BBB                     B",
            "                                   ",
            "                      F            ",
            "                                   ",
            "       1   [                      ]",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            '1': (x, y) => new MPowerPillar(x, y - 1.8, 'ball'),
            "[": (x, y) => new MGauntletDoor(x, y - 2.5, "left"),
            "]": (x, y) => new MGauntletDoor(x, y - 2.5, "right"),
            "F": (x, y) => new MPothead(x, y),
        },
    },
    // dev test
    9: {
        bitmap: [
            "#########################################",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                                       #",
            "#                           E           #",
            "#                                       #",
            "#########################################",
        ],  
        entities: {
            '1': (x, y) => new MPowerPillar(x, y - 1.8, 'ball'),
            '2': (x, y) => new MPowerPillar(x, y - 1.8, 'groundedTeleport'),
            '3': (x, y) => new MPowerPillar(x, y - 1.8, 'groundPound'),
            '4': (x, y) => new MPowerPillar(x, y - 1.8, 'fullTeleport'),
            'H': (x, y) => new MPothead(x, y),
            'Y': (x, y) => new MMimic(x, y - 0.3), // why is this Y? ftlogidk
            'M': (x, y) => new MMinitaur(x, y - 0.3),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'N': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "nl changed this line lol",
                "he probably wont change it back",
                "while typing this",
                "he noticed it was predicting his text",
                "this is really weird lol",
            ], 'pakala'),
            'K': (x, y) => new MNPC(x, y - 0.6, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'kili'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'sign'),
            'W': (x, y) => new MBreakWall(x, y, 'brickBreakWall', 'right'),
            // 'V': (x, y) => new MBreakWall(x, y, 'grassyBreakWall', 'right'),
            // 'U': (x, y) => new MBreakWall(x, y, 'mushroomBreakWall','right'),
        },
    },
};

const worldAssembly = [
    "0ℤλ         ml",
    "            nk",
    "            oj",
    "s         cdgi",
    "rqp6   XYabefh",
    "ZRQSTUVW w",
    "t PO   45x", 
    "uABCLKJI y",
    "v  DEFGH z3",
    "      MN21",
    "9",
];

