//each room has a name "A" for instance. World Assembly is where each room goes
const roomTemplates = {

    A: {
        bitmap: [
            "####################",
            "#                  #",
            "#  ###             #",
            "#                  #",
            "#          K       #",
            "#        ######    #",
            "#                  #",
            "#   ###            #",
            "#   #        S     #", 
            "#         ######   #",
            "#        ##        #",
            "#                  #",
            "#              ##  #",
            "#       @@@@       #",
            "#  ###              ",
            "#                   ",
            "#   BBBB            ",
            "# e E BB  C     N   ",
            "####################",
        ],  
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'N': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'pakala'),
            'K': (x, y) => new MNPC(x, y - 0.6, [
                "hiiiii",   
                "My name is Vicioustrex :P",
                ".",
                "..",
                "...",
                "You don't know me son *gasp*",
            ], 'kili'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'sign'),
        },
    },

    B: [
        "####################",
        "                   #",
        "#                  #",
        "#   ##             #",
        "#                  #",
        "#         ###      #",
        "#                  #",
        "#    ##            #",
        "#                  #",
        "#              ##  #",
        "#                  #",
        "#   ####           #",
        "#                  #",
        "#                  #",
        "         ##        #",
        "                   #",
        "                   #",
        "   c           d   #",
        "########     #######",
    ],

    C: [
        "####################",
        "#                  #",
        "#   ##             #",
        "#                  #",
        "#          ###      ",
        "#                  #",
        "#     ###          #",
        "#                  #",
        "#                   ",
        "#              ##  #",
        "#                  #",
        "#  ##              #",
        "#                  #",
        "#                   ",
        "#                   ",
        "#                   ",
        "####################",
    ],

    D: [
        "########     #######",
        "#                  #",
        "#                  #",
        "#        ##        #",
        "#                  #",
        "#  ##              #",
        "#                  #",
        "#           ###    #",
        "#                  #",
        "#    ##            #",
        "#                  #",
        "#              ##  #",
        "#                  #",
        "                   #",
        "                   #",
        "                   #",
        "####################",
    ],

};

const worldAssembly = [ 
    "AB",
    "CD",
];

